using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GrblPanel.My
{

	[System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"), System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase
	{

		private static MySettings defaultInstance = (MySettings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings());

		#region "My.Settings Auto-Save Functionality"

		private static bool addedHandler;

		private static object addedHandlerLockObject = new object();
		[System.Diagnostics.DebuggerNonUserCodeAttribute(), System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
		{
			if (MyProject.Application.SaveMySettingsOnExit) {
				GrblPanel.My.Settings.Save();
			}
		}
		#endregion

		public static MySettings Default {
			get {

				if (!addedHandler) {
					lock (addedHandlerLockObject) {
						if (!addedHandler) {
							MyProject.Application.Shutdown += AutoSaveSettings;
							addedHandler = true;
						}
					}
				}
				return defaultInstance;
			}
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string Port {
			get { return Convert.ToString(this["Port"]); }
			set { this["Port"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("115200")]
		public string Baud {
			get { return Convert.ToString(this["Baud"]); }
			set { this["Baud"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("False")]
		public bool JoggingUnitsMetric {
			get { return Convert.ToBoolean(this["JoggingUnitsMetric"]); }
			set { this["JoggingUnitsMetric"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G90 G10 L20 P0 X0 Y0 Z0")]
		public string Work0Cmd {
			get { return Convert.ToString(this["Work0Cmd"]); }
			set { this["Work0Cmd"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("True")]
		public bool StatusPollEnabled {
			get { return Convert.ToBoolean(this["StatusPollEnabled"]); }
			set { this["StatusPollEnabled"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("False")]
		public bool StatusVerbose {
			get { return Convert.ToBoolean(this["StatusVerbose"]); }
			set { this["StatusVerbose"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("200")]
		public string StatusPollInterval {
			get { return Convert.ToString(this["StatusPollInterval"]); }
			set { this["StatusPollInterval"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G90 G10 L20 P0 X0")]
		public string WorkX0Cmd {
			get { return Convert.ToString(this["WorkX0Cmd"]); }
			set { this["WorkX0Cmd"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G90 G10 L20 P0 Y0")]
		public string WorkY0Cmd {
			get { return Convert.ToString(this["WorkY0Cmd"]); }
			set { this["WorkY0Cmd"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G90 G10 L20 P0 Z0")]
		public string WorkZ0Cmd {
			get { return Convert.ToString(this["WorkZ0Cmd"]); }
			set { this["WorkZ0Cmd"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("100,50,10,5")]
		public string JoggingFRImperial {
			get { return Convert.ToString(this["JoggingFRImperial"]); }
			set { this["JoggingFRImperial"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("1,0.1,0.01,0.001")]
		public string JoggingFIImperial {
			get { return Convert.ToString(this["JoggingFIImperial"]); }
			set { this["JoggingFIImperial"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("10,1,0.1,0.01 ")]
		public string JoggingFIMEtric {
			get { return Convert.ToString(this["JoggingFIMEtric"]); }
			set { this["JoggingFIMEtric"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("1000,500,100,5")]
		public string JoggingFRMetric {
			get { return Convert.ToString(this["JoggingFRMetric"]); }
			set { this["JoggingFRMetric"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("17")]
		public string QBuffMaxSize {
			get { return Convert.ToString(this["QBuffMaxSize"]); }
			set { this["QBuffMaxSize"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("127")]
		public string RBuffMaxSize {
			get { return Convert.ToString(this["RBuffMaxSize"]); }
			set { this["RBuffMaxSize"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("2.5")]
		public string JoggingXRepeat {
			get { return Convert.ToString(this["JoggingXRepeat"]); }
			set { this["JoggingXRepeat"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("2.5")]
		public string JoggingZRepeat {
			get { return Convert.ToString(this["JoggingZRepeat"]); }
			set { this["JoggingZRepeat"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("2.5")]
		public string JoggingYRepeat {
			get { return Convert.ToString(this["JoggingYRepeat"]); }
			set { this["JoggingYRepeat"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("True")]
		public bool GCodePauseOnError {
			get { return Convert.ToBoolean(this["GCodePauseOnError"]); }
			set { this["GCodePauseOnError"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("False")]
		public bool GrblConnectOnLoad {
			get { return Convert.ToBoolean(this["GrblConnectOnLoad"]); }
			set { this["GrblConnectOnLoad"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("False")]
		public bool JoggingUseKeyboard {
			get { return Convert.ToBoolean(this["JoggingUseKeyboard"]); }
			set { this["JoggingUseKeyboard"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("False")]
		public bool LeftHandedGUI {
			get { return Convert.ToBoolean(this["LeftHandedGUI"]); }
			set { this["LeftHandedGUI"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G28")]
		public string MachineSpclPosition1 {
			get { return Convert.ToString(this["MachineSpclPosition1"]); }
			set { this["MachineSpclPosition1"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("G30")]
		public string MachineSpclPosition2 {
			get { return Convert.ToString(this["MachineSpclPosition2"]); }
			set { this["MachineSpclPosition2"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("$132")]
		public string GrblLastParamID {
			get { return Convert.ToString(this["GrblLastParamID"]); }
			set { this["GrblLastParamID"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("I2")]
		public string JoggingFIDefault {
			get { return Convert.ToString(this["JoggingFIDefault"]); }
			set { this["JoggingFIDefault"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("F2")]
		public string JoggingFRDefault {
			get { return Convert.ToString(this["JoggingFRDefault"]); }
			set { this["JoggingFRDefault"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("1.5")]
		public string StartupDelay {
			get { return Convert.ToString(this["StartupDelay"]); }
			set { this["StartupDelay"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string DefaultFileExt {
			get { return Convert.ToString(this["DefaultFileExt"]); }
			set { this["DefaultFileExt"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string IPAddress {
			get { return Convert.ToString(this["IPAddress"]); }
			set { this["IPAddress"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("0")]
		public string ConnectionType {
			get { return Convert.ToString(this["ConnectionType"]); }
			set { this["ConnectionType"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("Probe,G38.2 Z-30 F10")]
		public string Macro1 {
			get { return Convert.ToString(this["Macro1"]); }
			set { this["Macro1"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string Macro2 {
			get { return Convert.ToString(this["Macro2"]); }
			set { this["Macro2"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string Macro3 {
			get { return Convert.ToString(this["Macro3"]); }
			set { this["Macro3"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string Macro4 {
			get { return Convert.ToString(this["Macro4"]); }
			set { this["Macro4"] = value; }
		}

		[System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
		public string Macro5 {
			get { return Convert.ToString(this["Macro5"]); }
			set { this["Macro5"] = value; }
		}
		public MySettings()
		{
			PropertyChanged += settings_SettingsChanged;
			SettingChanging += traphere;
		}
	}
}

namespace GrblPanel.My
{

	[Microsoft.VisualBasic.HideModuleNameAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	static internal class MySettingsProperty
	{

		[System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]
		static internal global::GrblPanel.My.MySettings Settings {
			get { return global::GrblPanel.My.MySettings.Default; }
		}
	}
}
